Serve at uri
djmaze/tiddlywiki-docker pull request #11
Opened 2018-11-17 23:34 UTC by Whatang

Enable serving the tiddlywiki at a non-root path

[Serving the tiddlywiki at a non-root path](https://tiddlywiki.com/static/Using%2520a%2520custom%2520path%2520prefix%2520with%2520the%2520client-server%2520edition.html) requires 2 changes: 1 to the node call to tiddlywiki.js, and 1 to a configuration tiddler in the tiddlywiki itself.

This change creates an environment variable SERVE_URI. Setting this variable sets the prefix path argument on the node tiddlywiki.js invocation, and creates and populates the appropriate configuration tiddler.

2018-11-27 08:46 UTC, djmaze commented
First of all, thanks for the contribution. 

I am not quite sure if this is needed though. If you want to serve TW under a non-root path, that probably means you already have another site served at the root URL. In order to serve both, you need to have a webserver / reverse proxy in front of both. So you can just configure the webserver to serve TW under the prefix. Doesn't this work already, without configuration changes in TW?

2018-11-27 09:51 UTC, Whatang commented
Hi - yes, the reverse proxy is needed to serve the TW at the non-root path, however as per the linked page a configuration change is needed to the TW itself for this to work properly. Without the config change the TW cannot save changes correctly - the TW makes requests to the wrong path for interacting with the node server.

It might be possible to fix this by configuring your reverse proxy to make changes in the returned HTML/JS so that the correct path is set in the file served to the end user, but this is going to be brittle and require manual setup each time. This change serves the TW on the sub-path in the container, so that everything coming out of the container is correctly configured.

2018-11-29 07:39 UTC, pelag0s requested changes
Thanks for your explanation. Apart from the minor nitpick, it looks good to me.

2018-11-29 07:39 UTC, pelag0s commented on init-and-run-wiki
> +if [ -n "${SERVE_URI}" ]
Would you mind adopting the `if .. then` style used in the rest of the script? That would be more consistent. 

```suggestion
if [ -n "${SERVE_URI}" ]; then
```

2018-11-29 22:05 UTC, djmaze reviewed
Agree with the former review. Looks good otherwise.

2018-12-10 15:17 UTC, Whatang commented
I've made the suggested change and pushed to my repo.

2018-12-10 22:57 UTC, djmaze commented on init-and-run-wiki
> +  then
This occurrence too, please ;)

2018-12-12 13:00 UTC, Whatang commented on init-and-run-wiki
> +  then
Doh. Now?

2019-01-02 08:29 UTC, djmaze commented
Ok, thanks!

(Sorry for late response.)

2019-01-02 08:29 UTC, merged